server:
  port: 8082

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://awsajith.c6hsg00jd6yo.eu-north-1.rds.amazonaws.com:3306/library?useSSL=false&&serverTimezone=UTC
    username: admin
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: BOOK-SERVICE

  # JPA and Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: true
      format_sql: true

    #for service registry
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://51.20.108.137:8761/eureka/
  instance:
    hostname: localhost

